version: '3.8'

services:
  sei-mcp-server:
    image: 0xn1c0/sei-mcp-server:latest
    container_name: sei-mcp-server
    ports:
      - "${MCP_SERVER_PORT:-3333}:${MCP_SERVER_PORT:-3333}"
    environment:
      - NODE_ENV=production
      - MCP_SERVER_PORT=${MCP_SERVER_PORT:-3333}
      - PORT=${MCP_SERVER_PORT:-3333}
      - HOST=0.0.0.0
      - LOG_LEVEL=info
      - PRIVATE_KEY=${PRIVATE_KEY}
      # Server works without requiring private keys at startup
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config:ro
    restart: unless-stopped
    networks:
      - sei-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${MCP_SERVER_PORT:-3333}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Resource limits for production
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M

  # Optional: Nginx reverse proxy for SSL termination
  nginx:
    image: nginx:alpine
    container_name: sei-mcp-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/logs:/var/log/nginx
    depends_on:
      sei-mcp-server:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - sei-network
    profiles:
      - nginx
      - production

  # Optional: Monitoring with Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: sei-mcp-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    networks:
      - sei-network
    profiles:
      - monitoring

networks:
  sei-network:
    driver: bridge
    name: sei-mcp-network

volumes:
  prometheus_data:
    driver: local 