import fs from 'fs';
import path from 'path';

export interface EnvVariable {
  key: string;
  value: string;
  comment?: string;
  section?: string; // Section from env-example (e.g., "SERVICE PORTS")
}

export interface EnvSchema {
  [key: string]: {
    description?: string;
    section?: string;
    required?: boolean;
    type?: 'string' | 'number' | 'boolean' | 'url';
    default?: string;
  };
}

/**
 * Parse Seiling Buidlbox v2 .env file into structured format
 */
export function parseEnvFile(filePath: string): EnvVariable[] {
  if (!fs.existsSync(filePath)) {
    return [];
  }

  const content = fs.readFileSync(filePath, 'utf-8');
  const lines = content.split('\n');
  const variables: EnvVariable[] = [];
  let currentSection: string | undefined;

  for (const line of lines) {
    const trimmed = line.trim();
    
    // Skip empty lines
    if (!trimmed) {
      continue;
    }

    // Check for section comment (e.g., "# ===== SERVICE PORTS =====")
    const sectionMatch = trimmed.match(/^#\s*=+\s*(.+?)\s*=+/);
    if (sectionMatch) {
      currentSection = sectionMatch[1].trim();
      continue;
    }

    // Check for regular comment
    if (trimmed.startsWith('#')) {
      // Check if next line is a variable (it's a description)
      continue;
    }

    // Parse KEY=VALUE
    const match = trimmed.match(/^([A-Z_][A-Z0-9_]*)=(.*)$/);
    if (match) {
      const [, key, value] = match;
      // Remove quotes if present
      const unquotedValue = value.replace(/^["']|["']$/g, '');
      
      variables.push({
        key,
        value: unquotedValue,
        section: currentSection,
      });
    }
  }

  return variables;
}

/**
 * Parse Seiling Buidlbox v2 env-example.env to extract schema
 */
export function parseEnvSchema(filePath: string): EnvSchema {
  if (!fs.existsSync(filePath)) {
    return {};
  }

  const content = fs.readFileSync(filePath, 'utf-8');
  const lines = content.split('\n');
  const schema: EnvSchema = {};
  let currentSection: string | undefined;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const trimmed = line.trim();

    // Check for section comment
    const sectionMatch = trimmed.match(/^#\s*=+\s*(.+?)\s*=+/);
    if (sectionMatch) {
      currentSection = sectionMatch[1].trim();
      continue;
    }

    // Get comment description (line before the variable)
    if (trimmed.startsWith('#') && !trimmed.startsWith('# =')) {
      const nextLine = i + 1 < lines.length ? lines[i + 1].trim() : '';
      const varMatch = nextLine.match(/^([A-Z_][A-Z0-9_]*)=(.*)$/);
      
      if (varMatch) {
        const [, key] = varMatch;
        const description = trimmed.replace(/^#\s*/, '').trim();
        
        // Infer type from value
        const valueMatch = nextLine.match(/=(.*)$/);
        const defaultValue = valueMatch ? valueMatch[1].replace(/^["']|["']$/g, '') : undefined;
        
        let type: 'string' | 'number' | 'boolean' | 'url' = 'string';
        if (defaultValue) {
          if (defaultValue === 'yes' || defaultValue === 'no' || defaultValue === 'true' || defaultValue === 'false') {
            type = 'boolean';
          } else if (/^\d+$/.test(defaultValue)) {
            type = 'number';
          } else if (defaultValue.startsWith('http://') || defaultValue.startsWith('https://')) {
            type = 'url';
          }
        }

        // Check if required
        const required = description.toLowerCase().includes('required');

        schema[key] = {
          description,
          section: currentSection,
          required,
          type,
          default: defaultValue,
        };
      }
    }
  }

  return schema;
}

/**
 * Write Seiling Buidlbox v2 .env file from variables array
 */
export function writeEnvFile(filePath: string, variables: EnvVariable[]): void {
  // Group by section
  const bySection = new Map<string | undefined, EnvVariable[]>();
  
  for (const variable of variables) {
    const section = variable.section || 'Other';
    if (!bySection.has(section)) {
      bySection.set(section, []);
    }
    bySection.get(section)!.push(variable);
  }

  let content = '# Seiling Buidlbox Environment Configuration\n';
  content += '# Generated by Seiling Captain\n\n';

  for (const [section, vars] of bySection.entries()) {
    if (section && section !== 'Other') {
      content += `# =============================================================================\n`;
      content += `# ${section}\n`;
      content += `# =============================================================================\n\n`;
    }
    
    for (const variable of vars) {
      if (variable.comment) {
        content += `# ${variable.comment}\n`;
      }
      // Escape value if it contains spaces or special chars
      const value = variable.value.includes(' ') || variable.value.includes('#')
        ? `"${variable.value}"`
        : variable.value;
      content += `${variable.key}=${value}\n`;
    }
    
    content += '\n';
  }

  fs.writeFileSync(filePath, content, 'utf-8');
}

/**
 * Create backup of Seiling Buidlbox v2 .env file
 */
export function backupEnvFile(filePath: string): string {
  if (!fs.existsSync(filePath)) {
    return '';
  }

  const backupPath = `${filePath}.backup.${Date.now()}`;
  fs.copyFileSync(filePath, backupPath);
  return backupPath;
}

/**
 * Validate Seiling Buidlbox v2 env variables against schema
 */
export function validateEnvVariables(
  variables: EnvVariable[],
  schema: EnvSchema
): { valid: boolean; errors: string[] } {
  const errors: string[] = [];
  const varMap = new Map(variables.map(v => [v.key, v]));

  // Check required fields
  for (const [key, schemaEntry] of Object.entries(schema)) {
    if (schemaEntry.required && !varMap.has(key)) {
      errors.push(`Required variable ${key} is missing`);
    }
  }

  // Validate types
  for (const variable of variables) {
    const schemaEntry = schema[variable.key];
    if (schemaEntry) {
      if (schemaEntry.type === 'number') {
        if (variable.value && isNaN(Number(variable.value))) {
          errors.push(`${variable.key} must be a number`);
        }
      } else if (schemaEntry.type === 'boolean') {
        const validValues = ['yes', 'no', 'true', 'false', '1', '0', 'true', 'false'];
        if (variable.value && !validValues.includes(variable.value.toLowerCase())) {
          errors.push(`${variable.key} must be a boolean (yes/no or true/false)`);
        }
      } else if (schemaEntry.type === 'url') {
        try {
          new URL(variable.value);
        } catch {
          errors.push(`${variable.key} must be a valid URL`);
        }
      }
    }
  }

  return {
    valid: errors.length === 0,
    errors,
  };
}

/**
 * Get Seiling Buidlbox v2 env file paths (repo root)
 */
export function getEnvPaths(repoRoot?: string) {
  // Auto-detect repo root if not provided
  const actualRepoRoot = repoRoot || process.env.REPO_ROOT || (() => {
    const { findRepoRoot } = require('./serviceCatalog');
    return findRepoRoot();
  })();
  
  return {
    env: path.join(actualRepoRoot, '.env'),
    example: path.join(actualRepoRoot, 'env-example.env'), // Seiling Buidlbox v2 schema file
  };
}

