services:
  ollama:
    image: ollama/ollama:latest
    container_name: seiling-ollama
    restart: unless-stopped
    environment:
      - OLLAMA_CONTEXT_LENGTH=8192
      - OLLAMA_FLASH_ATTENTION=1
      - OLLAMA_KV_CACHE_TYPE=q8_0
      - OLLAMA_MAX_LOADED_MODELS=2
      - ENABLE_OLLAMA=${ENABLE_OLLAMA:-yes}
    volumes:
      - ollama_storage:/root/.ollama
    ports:
      - "${OLLAMA_PORT:-11434}:11434"
    networks:
      - seiling_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 20s
      retries: 10
      start_period: 120s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ollama.rule=Host(`${OLLAMA_SUBDOMAIN:-ollama}.${BASE_DOMAIN_NAME:-localhost}`)"
      - "traefik.http.routers.ollama.entrypoints=websecure"
      - "traefik.http.routers.ollama.tls.certresolver=myresolver"
      - "traefik.http.services.ollama.loadbalancer.server.port=11434"
    entrypoint: >
      sh -c 'if [ "$ENABLE_OLLAMA" = "yes" ] || [ "$ENABLE_OLLAMA" = "true" ]; then /bin/ollama serve; else echo "Ollama disabled by ENABLE_OLLAMA=$ENABLE_OLLAMA"; sleep infinity; fi' 