services:
  sei-mcp-server:
    image: 0xn1c0/sei-mcp-server:multi
    container_name: seiling-sei-mcp-server
    restart: unless-stopped
    environment:
      - MCP_SERVER_PORT=${MCP_SERVER_PORT:-5004}
      - PRIVATE_KEY=${SEI_PRIVATE_KEY}
      - SEI_PRIVATE_KEY=${SEI_PRIVATE_KEY}
      - RPC_URL=${RPC_URL:-https://evm-rpc.sei-apis.com}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - DEBUG=${DEBUG:-false}
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - ENABLE_SEI_MCP=${ENABLE_SEI_MCP:-yes}
      - NODE_ENV=production
      - HOST=0.0.0.0
    ports:
      - "${MCP_SERVER_PORT:-5004}:${MCP_SERVER_PORT:-5004}"
    volumes:
      - sei_mcp_storage:/app/.sei-mcp
      - sei_mcp_logs:/app/logs
      - sei_mcp_config:/app/config
    networks:
      - seiling_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${MCP_SERVER_PORT:-5004}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.seimcp.rule=Host(`${SEI_MCP_SUBDOMAIN:-mcp}.${BASE_DOMAIN_NAME:-localhost}`)"
      - "traefik.http.routers.seimcp.entrypoints=websecure"
      - "traefik.http.routers.seimcp.tls.certresolver=myresolver"
      - "traefik.http.services.seimcp.loadbalancer.server.port=${MCP_SERVER_PORT:-5004}"

volumes:
  sei_mcp_storage:
    driver: local
  sei_mcp_logs:
    driver: local
  sei_mcp_config:
    driver: local
