services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: seiling-qdrant
    restart: unless-stopped
    environment:
      - ENABLE_QDRANT=${ENABLE_QDRANT:-yes}
    volumes:
      - qdrant_data:/qdrant/storage
    ports:
      - "${QDRANT_PORT:-6333}:6333"
      - "${QDRANT_GRPC_PORT:-6334}:6334"
    networks:
      - seiling_network

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qdrant.rule=Host(`${QDRANT_SUBDOMAIN:-qdrant}.${BASE_DOMAIN_NAME:-localhost}`)"
      - "traefik.http.routers.qdrant.entrypoints=websecure"
      - "traefik.http.routers.qdrant.tls.certresolver=myresolver"
      - "traefik.http.services.qdrant.loadbalancer.server.port=6333"
    entrypoint: >
      sh -c 'if [ "$ENABLE_QDRANT" = "yes" ] || [ "$ENABLE_QDRANT" = "true" ]; then /qdrant/qdrant; else echo "Qdrant disabled by ENABLE_QDRANT=$ENABLE_QDRANT"; sleep infinity; fi' 