services:
  seiling-builder:
    container_name: seiling-builder
    build:
      context: ./packages/seiling-builder
    ports:
      - "${BUILDER_PORT:-3002}:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

